version: "3.7"

services:
    redis:
        hostname: redis
        image: redislabs/redismod:latest
        volumes:
          - ${PWD-.}/redis:/data
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            swlor_network:
                

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: unless-stopped
        links:
            - "redis:redis"
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8081:8081"
        networks:
            swlor_network:

    zipkin: 
        hostname: zipkin
        image: openzipkin/zipkin:latest
        restart: unless-stopped
        ports:
            - "9411:9411"
        networks:
            swlor_network:

    otel-collector:
        hostname: otel-collector
        image: otel/opentelemetry-collector-contrib-dev:latest
        depends_on:
            - zipkin
        volumes:
            - ${PWD-.}/otel-config.yaml:/etc/otel/config.yaml
        ports: 
            - "1888:1888"   # pprof extension
            - "13133:13133" # health_check extension
            - "4317:4317"        # OTLP gRPC receiver
            - "55679:55679" # zpages extension        
        networks:
            swlor_network:


    #grafana:
    #    hostname: grafana
    #    image: grafana/grafana:6.0.1
    #    restart: unless-stopped
    #    environment:
    #        - GF_SECURITY_ADMIN_PASSWORD=admin
    #    ports:
    #        - "3000:3000"
    #    depends_on:
    #        - jaeger
    #    volumes:
    #        - ./grafana-provisioning:/etc/grafana/provisioning
    #    networks:
    #        swlor_network:
            

    swlor-server:
        hostname: nwnx-server
        image: nwnxee/unified:latest
        env_file: ${PWD-.}/swlor.env
        stdin_open: true
        tty: true
        depends_on:
            - redis
            - otel-collector
        volumes:
            - ${PWD-.}/logs:/nwn/run/logs.0
            - ${PWD-.}/:/nwn/home
            - ${PWD-.}/logs:/nwn/data/bin/linux-x86/logs.0
            - ${PWD-.}/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
        ports:
            - "5121:5121/udp"
        networks:
          swlor_network:
         
          
networks:
    swlor_network:
