version: "3.7"

services:
    redis:
        hostname: redis
        image: redislabs/redismod:latest
        volumes:
          - ${PWD-.}/redis:/data
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            swlor_network:
                

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: unless-stopped
        links:
            - "redis:redis"
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8081:8081"
        networks:
            swlor_network:
  

    prometheus: 
        hostname: prometheus
        image: prom/prometheus
        restart: unless-stopped
        ports:
            - "9090:9090"        
        networks:
            swlor_network:

    grafana:
        hostname: grafana
        image: grafana/grafana:6.0.1
        restart: unless-stopped
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        ports:
            - "3000:3000"
        depends_on:
            - prometheus
        volumes:
            - ./grafana-provisioning:/etc/grafana/provisioning
        networks:
            swlor_network:
            

    swlor-server:
        hostname: nwnx-server
        image: nwnxee/unified:latest
        env_file: ${PWD-.}/swlor.env
        stdin_open: true
        tty: true
        depends_on:
            - redis
            - prometheus
        volumes:
            - ${PWD-.}/logs:/nwn/run/logs.0
            - ${PWD-.}/:/nwn/home
            - ${PWD-.}/logs:/nwn/data/bin/linux-x86/logs.0
            - ${PWD-.}/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
        ports:
            - "5121:5121/udp"
        networks:
          swlor_network:
         
          
networks:
    swlor_network:
